spring:
  profiles: dev
  datasource:
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.136.40.39:3306/food?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    # formatSQL得这样写
    properties:
      hibernate:
        format_sql: true
server:
  port: 5910

---

spring:
  profiles: test
server:
  port: 9002

---

spring:
  profiles: proc
server:
  port: 9003

---

spring:
  profiles:
    active: dev

# 指明使用的是 dev（开发环境）下的配置

