name: Deploy site files

on:
  push:
    branches:
      - master # 只在master上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Running Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: 缓存 Maven 依赖
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: 编译代码
        run: mvn -f ./back_end/pom.xml compile
      - name: Deploy the JAR file to the remote server
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate the package
        run: mvn -B package --file ./back_end/pom.xml -Dmaven.test.skip=true
      - name: 将 JAR 包部署到服务器
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./back_end/target/menu-0.0.1-SNAPSHOT.jar
          remote: /jarManager/menu.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey : ${{ secrets.KEY }}
      - name: 在服务器上执行 java -jar，请确保服务器安装了 JDK
        if: always()
        uses: fifsky/ssh-action@master
        with:
          command: | # 命令中的 & 表示在后台运行进程
            cd /jarManager/ && java -jar menu.jar &
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY}}
          args: "-tt"